volumes:
  postgres-data:

services:
  app:
    container_name: javadev
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in db container
        MYSQL_PASSWORD: password
        MYSQL_USER: user
        MYSQL_DB: db
        MYSQL_HOSTNAME: mysqldb
        MYSQL_ROOT_PASSWORD: root

    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    # volumes:
    #   - ../../:/var/lib/mysql/
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DB: db
      MYSQL_ROOT_PASSWORD: root

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)